import Head from "next/head";
import React from "react";
import { Checkbox, Header, NavBar } from "../components/ui";
import Layout from "../components/ui/Layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <footer></footer>
    </Layout>
  );
}
