import Head from "next/head";
import React, { ReactElement, useEffect } from "react";
import { useRouter } from "next/router";

export default function Splash() {
  const router = useRouter();

  // login logic here for routing to correct page
  useEffect(() => {
    router.push("/home");
  }, []);

  return (
    <main className="px-8 py-2">
      <Head>
        <title>Seat Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </main>
  );
}

Splash.setLayout = function getLayout(page: ReactElement) {
  return <div>{page}</div>;
};
