import Head from "next/head";
import React from "react";
import Checkbox from "../components/ui/Checkbox";
import PageHeader from "../components/ui/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader />
      <Checkbox onChange={() => console.log("pressed")} height={"16"} width={"16"} />
      <footer></footer>
    </div>
  );
}
