import React, { ReactElement } from "react";
import Head from "next/head";
import client from "../../apollo-client";
import { gql } from "@apollo/client";
import { Office } from "../../types";
import { OfficesTable } from "./components";
import { Layout, Button, PageTitle } from "../../components/ui";

interface OfficesProps {
  offices: Office[];
}

export default function OfficesPage({ offices }: OfficesProps) {
  return (
    <main className="px-8 py-2">
      <Head>
        <title>Seat Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle>
        Offices
        <Button primary onClick={() => {}}>
          Add new
        </Button>
      </PageTitle>
      <OfficesTable data={offices} />
    </main>
  );
}

OfficesPage.setLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export async function getStaticProps() {
  const data = await officesQuery();
  return {
    props: {
      offices: data.offices,
    },
  };
}

export const officesQuery = async () => {
  const { data } = await client.query({
    query: gql`
      query Offices {
        offices {
          id
          name
          createdAt
        }
      }
    `,
  });
  return data;
};
