import React, { ReactElement } from "react";
import Head from "next/head";
import { Layout, PageTitle } from "../../components/ui";

interface SettingsProps {}

export default function SettingsPage({}: SettingsProps) {
  return (
    <main className="px-8 py-2">
      <Head>
        <title>Seat Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle>Settings</PageTitle>
    </main>
  );
}

SettingsPage.setLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};
