import Head from "next/head";
import React, { ReactElement } from "react";
import Layout from "../../components/ui/Layout";
import ReservationsCard from "./components/reservationsCard";

export default function Home() {
  return (
    <main className="px-8 py-2">
      <Head>
        <title>Seat Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-semibold text-2xl mb-8">Your Reservations</div>
      <ReservationsCard />
    </main>
  );
}

Home.setLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};
