import React, { ReactElement } from "react";
import Head from "next/head";
import client from "../../apollo-client";
import { Layout, Button, Card, PageTitle } from "../../components/ui";
import { BuildingsTable } from "./components";
import { Building } from "../../types";
import { getBuildings } from "../../services/queries";

interface BuildingsProps {
  buildings: Building[];
}

export default function BuildingsPage({ buildings }: BuildingsProps) {
  return (
    <main className="px-8 py-2">
      <Head>
        <title>Seat Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle>
        Buildings
        <Button primary onClick={() => {}}>
          Add new
        </Button>
      </PageTitle>
      <Card className="mb-8">
        <div className="flex justify-between text-5xl">
          <div>📈</div>|<div>📊</div>|<div>💹</div>
        </div>
      </Card>
      <BuildingsTable data={buildings} />
    </main>
  );
}

BuildingsPage.setLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export async function getStaticProps() {
  const { data } = await client.query({ query: getBuildings });
  return {
    props: {
      buildings: data.buildings,
    },
  };
}
