import Head from "next/head";
import React, { ReactElement } from "react";
import { Layout, Button, Card, PageTitle } from "../../components/ui";
import { BuildingsTable } from "./components";

export default function Buildings() {
  return (
    <main className="px-8 py-2">
      <Head>
        <title>Seat Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle>
        Buildings
        <Button primary onClick={() => {}}>
          Add new
        </Button>
      </PageTitle>
      <Card className="mb-8">
        <div className="flex justify-between text-5xl">
          <div>📈</div>|<div>📊</div>|<div>💹</div>
        </div>
      </Card>
      <BuildingsTable />
    </main>
  );
}

Buildings.setLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};
