import React, { ReactElement } from "react";
import Head from "next/head";
import client from "../../apollo-client";
import { Layout, Button, Card, PageTitle } from "../../components/ui";
import { BuildingsTable } from "./components";
import { Building } from "../../types";
import BuildingModal from "./components/BuildingModal";
import { refreshData, getBuildings, createBuilding } from "../../services";
import { useRouter } from "next/router";
import { useModalStore } from "../../stores";
import { useMutation } from "@apollo/client";

interface BuildingsProps {
  buildings: Building[];
}

export default function BuildingsPage({ buildings }: BuildingsProps) {
  const router = useRouter();
  const openModal = useModalStore((state) => state.setIsOpen);
  const [addBuilding, { data, loading, error }] = useMutation(createBuilding);

  const addBuildingModal = () => {
    openModal(true, {
      cancelText: "Cancel",
      confirmText: "Save",
      content: <BuildingModal />,
      data: { buildingName: "" },
      title: "Add Building",
      onConfirmAction: (data) => {
        addBuilding({
          variables: {
            name: data.buildingName,
          },
        });
        refreshData(router);
      },
    });
  };

  return (
    <main className="px-8 py-2">
      <Head>
        <title>Seat Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle>
        Buildings
        <Button primary onClick={() => addBuildingModal()}>
          Add new
        </Button>
      </PageTitle>
      <Card className="mb-8">
        <div className="flex justify-between text-5xl">
          <div>📈</div>|<div>📊</div>|<div>💹</div>
        </div>
      </Card>
      <BuildingsTable data={buildings} />
    </main>
  );
}

BuildingsPage.setLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export async function getStaticProps() {
  const { data } = await client.query({ query: getBuildings });
  return {
    props: {
      buildings: data.buildings,
    },
  };
}
